version: '3'

services:
  # frontend:

  #   null


  backend:
    build: ./service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/advertisement_db
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:11
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: advertisement_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"
    # pgadmin:
    #   image: dpage/pgadmin4
    #   restart: unless-stopped
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: service@service.com
    #     PGADMIN_DEFAULT_PASSWORD: postgres
    #     PGADMIN_LISTEN_PORT: 5050
    #   network_mode: service:db

volumes:
  postgres-data: null
